const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const crypto=require('node:crypto');
const scanner=require('../web/static/scanner.js');
const {harness,deferred,flush,pngHeader}=require('./scanner_harness.cjs');
const code='SHOPDEMO-000001',good=[{rawValue:code,format:'code_128'}];

test('vendored decoder is the exact pinned npm UMD artifact',()=>{
 const bytes=fs.readFileSync(require.resolve('../web/static/zxing-library-0.23.0.min.js'));
 assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),'3ede94153fb0c5b67a12d7adff6decd827c2b22714fdc6faecf27a8f20937ea6');
 for(const name of ['ZXING-LICENSE','ZXING-NOTICES','TS-CUSTOM-ERROR-LICENSE','BARCODE-LICENSE'])assert.ok(fs.statSync(`${__dirname}/../web/static/${name}`).size>500);
});
test('camera starts only on explicit action with no audio and rear-facing preference',async()=>{const h=harness();assert.equal(h.stats.requested,0);assert.equal(h.root.hidden,false);await h.instance.startCamera();assert.equal(h.stats.requested,1);assert.equal(h.stats.constraints.audio,false);assert.equal(h.stats.constraints.video.facingMode.ideal,'environment');h.instance.stop();assert.equal(h.stats.stopped,1);assert.equal(h.video.srcObject,null);assert.equal(h.video.hidden,true);assert.equal(h.timers.size,0);});
test('recognition populates fields then stops without a submit or repeated pick',async()=>{const h=harness({results:good});await h.instance.startCamera();await h.tick();assert.equal(h.input.value,code);assert.equal(h.source.value,'camera');assert.equal(h.format.value,'Code128');assert.match(h.parts.status.textContent,/Nothing has been picked/);assert.equal(h.stats.stopped,1);assert.equal(h.stats.submitted,0);assert.equal(h.timers.size,0);await h.tick();assert.equal(h.stats.detects,1);assert.deepEqual(h.input.events,['input','change']);assert.equal(h.input.focused,true);});
test('multiple and unsupported labels never populate or submit',async()=>{for(const results of [[...good,...good],[{rawValue:'http://example.test',format:'qr_code'}],[{rawValue:'000000000101',format:'code_128'}]]){const h=harness({results});await h.instance.startCamera();await h.tick();assert.equal(h.input.value,'');assert.equal(h.stats.stopped,1);assert.equal(h.stats.submitted,0);assert.equal(h.parts.status.dataset.error,'true');}});
test('double Start and repeated Start while permission pending request exactly one stream',async()=>{const permission=deferred(),h=harness({permission});const first=h.instance.startCamera();await h.instance.startCamera();assert.equal(h.stats.requested,1);permission.resolve(h.media);await first;await h.instance.startCamera();assert.equal(h.stats.requested,1);h.instance.stop();});
test('Stop before late permission releases every track and cannot restart the preview',async()=>{const permission=deferred(),h=harness({permission});const first=h.instance.startCamera();h.instance.stop();assert.equal(h.parts.start.disabled,true);permission.resolve(h.media);await first;assert.equal(h.stats.stopped,1);assert.equal(h.stats.played,0);assert.equal(h.video.srcObject,null);assert.equal(h.parts.start.disabled,false);assert.equal(h.timers.size,0);});
test('permission rejection has useful retry/manual fallback',async()=>{const error=Object.assign(new Error('denied'),{name:'NotAllowedError'}),h=harness({permissionError:error});await h.instance.startCamera();assert.match(h.parts.status.textContent,/permission was not granted/);assert.equal(h.parts.start.disabled,false);assert.equal(h.video.hidden,true);assert.equal(h.input.disabled,false);assert.equal(h.timers.size,0);});
test('no camera and insecure origin retain ordinary manual entry',async()=>{for(const mode of ['missing','insecure']){const h=harness();if(mode==='missing')h.env.navigator.mediaDevices=null;else h.env.isSecureContext=false;await h.instance.startCamera();assert.equal(h.stats.requested,0);assert.match(h.parts.status.textContent,/type the code/);assert.equal(h.input.disabled,false);}});
test('native is used only when code_128 is advertised and failure falls back to pixels',async()=>{for(const options of [{formats:['qr_code']},{detectError:new Error('native unavailable')},{native:false}]){const h=harness(options);await h.instance.startCamera();await h.tick();if(options.formats)assert.equal(h.stats.nativeConstructed,0);assert.equal(h.input.value,'');assert.equal(h.parts.status.dataset.error,'false');assert.ok(h.stats.draws>0);h.instance.stop();}});
test('a late native decode cannot populate code after Stop or a newer form',async()=>{const detectPromise=deferred(),h=harness({detectPromise});await h.instance.startCamera();const pending=h.tick();await flush();h.instance.stop();detectPromise.resolve(good);await pending;assert.equal(h.input.value,'');assert.equal(h.stats.stopped,1);assert.equal(h.timers.size,0);assert.equal(h.parts.start.disabled,false);});
test('frames are serial, bounded, and scan session has a finite pause timer',async()=>{const detectPromise=deferred(),h=harness({detectPromise});await h.instance.startCamera();const pending=h.tick();await flush();await h.tick();assert.equal(h.stats.detects,1);const timeout=[...h.timers.values()].find(v=>v.ms===scanner.LIMITS.sessionMS);assert.ok(timeout);timeout.fn();detectPromise.resolve([]);await pending;assert.equal(h.stats.stopped,1);assert.equal(h.timers.size,0);});
test('track loss and canvas/play errors stop the stream and expose recovery',async()=>{for(const options of [{playError:new Error('lost')},{pixelError:new Error('canvas'),native:false}]){const h=harness(options);await h.instance.startCamera();await h.tick();assert.equal(h.stats.stopped,1);assert.match(h.parts.status.textContent,/type the code/);assert.equal(h.timers.size,0);}const h=harness();await h.instance.startCamera();h.track.onended();assert.equal(h.stats.stopped,1);assert.equal(h.video.hidden,true);});
test('manual edits and form submission stop the camera without submitting through JS',async()=>{const h=harness();await h.instance.startCamera();h.source.value='camera';h.input.emit('input');assert.equal(h.source.value,'manual');assert.equal(h.stats.stopped,1);await h.instance.startCamera();h.form.emit('submit');assert.equal(h.stats.stopped,2);assert.equal(h.stats.submitted,0);});
for(const trigger of ['hidden','pagehide','popstate','remove','htmx','revoked','pause'])test(`${trigger} stops tracks/timers and never implicitly resumes`,async()=>{const h=harness({install:true});await h.instance.startCamera();if(trigger==='hidden'){h.doc.hidden=true;h.doc.emit('visibilitychange');h.doc.hidden=false;h.doc.emit('visibilitychange');}if(trigger==='pagehide'||trigger==='popstate')h.env.emit(trigger);if(trigger==='remove'){h.root.isConnected=false;h.installation.mount();}if(trigger==='htmx')h.doc.emit('htmx:beforeCleanupElement',{elt:h.root});if(trigger==='revoked')h.doc.emit('handheld:revoked');if(trigger==='pause')h.doc.emit('handheld:pause');assert.equal(h.stats.stopped,1);assert.equal(h.timers.size,0);h.env.emit('pageshow');assert.equal(h.stats.requested,1);assert.equal(h.video.srcObject,null);});
test('removed form ignores late permission',async()=>{const permission=deferred(),h=harness({install:true,permission});const pending=h.instance.startCamera();h.root.isConnected=false;h.installation.mount();permission.resolve(h.media);await pending;assert.equal(h.stats.stopped,1);assert.equal(h.stats.played,0);assert.equal(h.input.value,'');});
test('photo stays local, populates for explicit review and releases its object URL',async()=>{const h=harness({results:good});await h.photoFile({size:24,type:'image/png',arrayBuffer:async()=>pngHeader()});assert.equal(h.stats.requested,0);assert.equal(h.input.value,code);assert.equal(h.source.value,'photo');assert.equal(h.stats.submitted,0);assert.equal(h.stats.urls.length,1);assert.deepEqual(h.stats.revoked,h.stats.urls);assert.equal(h.parts.photo.value,'');assert.equal(h.parts.start.disabled,false);});
test('oversized files, unsupported types and header pixel bombs are rejected before bitmap allocation',async()=>{for(const file of [{size:scanner.LIMITS.fileBytes+1,type:'image/png'},{size:24,type:'image/svg+xml'},{size:24,type:'image/png',arrayBuffer:async()=>pngHeader(16000,16000)}]){const h=harness();await h.photoFile(file);assert.equal(h.stats.urls.length,0);assert.equal(h.stats.requested,0);assert.equal(h.stats.submitted,0);assert.equal(h.parts.status.dataset.error,'true');assert.equal(h.parts.start.disabled,false);}});
test('photo errors release URL and remain retryable',async()=>{const h=harness({imageError:true});await h.photoFile({size:24,type:'image/png',arrayBuffer:async()=>pngHeader()});assert.deepEqual(h.stats.revoked,h.stats.urls);assert.equal(h.parts.start.disabled,false);assert.equal(h.input.value,'');assert.equal(h.parts.status.dataset.error,'true');});
test('Stop during photo bytes ignores late decoding and does not create URL',async()=>{const bytes=deferred(),h=harness({results:good});const pending=h.photoFile({size:24,type:'image/png',arrayBuffer:()=>bytes.promise});h.instance.stop();bytes.resolve(pngHeader());await pending;assert.equal(h.stats.urls.length,0);assert.equal(h.input.value,'');assert.equal(h.parts.start.disabled,false);});
test('photo parser bounds malformed containers and supports header dimensions',()=>{assert.deepEqual(scanner.photoSize(pngHeader(600,300),'image/png'),{width:600,height:300});for(const data of [new ArrayBuffer(0),new ArrayBuffer(30),pngHeader(0,0)])assert.throws(()=>scanner.photoSize(data,'image/png'));});

test('employee scan auto-reviews identity once without ever submitting a pick or weight',async()=>{
 for(const path of ['/handheld/scan','/handheld/pick','/handheld/weight/confirm']){
  const h=harness({results:good});h.root.dataset.scanAutoReview='true';h.form.getAttribute=n=>n==='action'?path:null;
  await h.instance.startCamera();await h.tick();await h.tick();
  assert.equal(h.stats.submitted,path==='/handheld/scan'?1:0);assert.equal(h.stats.stopped,1);assert.equal(h.stats.detects,1);assert.equal(h.timers.size,0);
 }
});


test('auto-review photo cleanup cannot unlock or restart a scanner while its form is saving',async()=>{
 const h=harness({results:good});h.root.dataset.scanAutoReview='true';h.form.getAttribute=()=>'/handheld/scan';
 h.form.requestSubmit=()=>{h.stats.submitted++;h.input.disabled=true;h.parts.start.disabled=true;h.parts.start.dataset.handheldBusy='1';};
 await h.photoFile({size:24,type:'image/png',arrayBuffer:async()=>pngHeader()});
 assert.equal(h.stats.submitted,1);assert.equal(h.parts.start.disabled,true);
 await h.instance.startCamera();assert.equal(h.stats.requested,0);
});
